trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      version: '8.0.x'

  - script: dotnet msbuild RecordsApi/RecordsApi.csproj -restore -p:Configuration=Release
    displayName: 'Build API'

  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'

  - script: |
      cd ClientApp
      npm ci
      npm run build
    displayName: 'Build client'
