image: mcr.microsoft.com/dotnet/sdk:8.0

pipelines:
  default:
    - step:
        name: Build API
        script:
          - dotnet cake RecordsApi/build.cake --target=Build
    - step:
        name: Build client
        image: node:22
        script:
          - cd ClientApp
          - npm ci
          - npm run build
